export const levelz: string[] = [
	"",
	"Advanced Studies (CAS, DAS)",
	"Bachelor's Degree Programme",
	"Diploma Programme",
	"Doctorate",
	"Master of Advanced Studies",
	"Master's Degree Programme",
	"Mobility Students",
	"Teaching Certificate",
	"Teaching Diploma",
]

export const deps: string[] = [
	"",
	"D-ARCH",
	"D-BAUG",
	"D-BIOL",
	"D-BSSE",
	"D-CHAB",
	"D-EAPS",
	"D-GESS",
	"D-HEST",
	"D-INFK",
	"D-ITET",
	"D-MATH",
	"D-MATL",
	"D-MAVT",
	"D-MTEC",
	"D-PHYS",
	"D-USYS"
]

export const listUniversityDegrees: string[] = [
    "Agricultural Sciences Bachelor",
    "Agricultural Sciences Master",
    "Agricultural Sciences TC",
    "Applied Geophysics Master",
    "Architecture Bachelor",
    "Architecture Master",
    "Atmospheric and Climate Science Master",
    "Biochemistry – Chemical Biology Bachelor",
    "Biochemistry - Chemical Biology Master",
    "Biology Bachelor",
    "Biology (General Courses)",
    "Biology Master",
    "Biology Teaching Diploma",
    "Biomedical Engineering Master",
    "Biotechnology Master",
    "CAS in Advanced Materials and Processes",
    "CAS in Applied Earth Sciences",
    "CAS in Applied Machine Learning &amp; Information Processing",
    "CAS in Applied Statistical Data Science",
    "CAS in Applied Technology: R&amp;D and Innovation",
    "CAS in Artificial Intelligence and Software Development",
    "CAS in Cloud and Mobile Computing",
    "CAS in Computer Science",
    "CAS in Cyber Security",
    "CAS in Data and Machine Learning",
    "CAS in Digital Clinical Trials",
    "CAS in Digital Health",
    "CAS in Entrepreneurial Leadership in Technology Ventures",
    "CAS in Future Heritage",
    "CAS in Future of Spatial Development",
    "CAS in Future Transport Systems: New Business Models",
    "CAS in Future Transport Systems: Systemic Aspects",
    "CAS in Future Transport Systems: Technology Potential",
    "CAS in Geoinformation Systems and Analysis",
    "CAS in Global Cooperation and Sustainable Development",
    "CAS in Infrastructure Construction Management",
    "CAS in Machine Learning in Finance and Insurance",
    "CAS in Nutrition for Disease Prevention and Health",
    "CAS in Nutrition in Medicine",
    "CAS in Pharmaceuticals - From Research to Market",
    "CAS in Preservation",
    "CAS in Public Governance and Administration",
    "CAS in Radiopharmaceutical Chemistry, Radiopharmacy",
    "CAS in Regenerative Materials - Hygrothermal Specialisation",
    "CAS in Regenerative Materials - Structural Specialisation",
    "CAS in Regenerative Systems: Beyond Systems Thinking",
    "CAS in Regenerative Systems: Sustainability to Regeneration",
    "CAS in Regenerative Systems: Systemic Design",
    "CAS in Regulatory Thinking",
    "CAS in Robotics",
    "CAS in Seismic Evaluation and Retrofitting",
    "CAS in Spatial Development and Planning Practice",
    "CAS in Technology and Public Policy: Impact Analysis",
    "CAS in Technology and Public Policy: Policy Process",
    "Chemical and Bioengineering Master",
    "Chemical Engineering Bachelor",
    "Chemistry Bachelor",
    "Chemistry (General Courses)",
    "Chemistry Master",
    "Chemistry Teaching Diploma",
    "Civil Engineering Bachelor",
    "Civil Engineering (General Courses)",
    "Civil Engineering Master",
    "Comparative and International Studies Master",
    "Computational Biology and Bioinformatics Master",
    "Computational Science and Engineering Bachelor",
    "Computational Science and Engineering Master",
    "Computer Science Bachelor",
    "Computer Science (General Courses)",
    "Computer Science Master",
    "Computer Science TC",
    "Computer Science Teaching Diploma",
    "Cyber Security Master",
    "DAS in Applied Statistical Data Science",
    "DAS in Cyber Security",
    "DAS in Data Science",
    "DAS in Information Technology and Electrical Engineering",
    "DAS in Military Sciences",
    "DAS in Regenerative Materials",
    "DAS Preparation for the Swiss Federal Examination in Pharmacy",
    "Data Science Master",
    "Doctorate Architecture",
    "Doctorate Biology",
    "Doctorate Biosystems Science and Engineering",
    "Doctorate Chemistry and Applied Biosciences",
    "Doctorate Civil, Environmental and Geomatic Engineering",
    "Doctorate Computer Science",
    "Doctorate Earth and Planetary Sciences",
    "Doctorate Environmental Systems Sciences",
    "Doctorate Health Sciences and Technology",
    "Doctorate Humanities, Social and Political Sciences",
    "Doctorate Information Technology and Electrical Engineering",
    "Doctorate Management, Technology, and Economics",
    "Doctorate Materials Science",
    "Doctorate Mathematics",
    "Doctorate Mechanical and Process Engineering",
    "Doctorate Physics",
    "Earth and Climate Sciences Bachelor",
    "Earth Sciences Master",
    "Educational Science for Teaching Diploma and TC",
    "Electrical Engineering and Information Technology Bachelor",
    "Electrical Engineering and Information Technology Master",
    "Electrical Engineering and Information Technology TC",
    "EMBA ETH HSG (emba X)",
    "Energy Science and Technology Master",
    "Environmental Engineering Bachelor",
    "Environmental Engineering Master",
    "Environmental Sciences Bachelor",
    "Environmental Sciences Master",
    "Environmental Studies TC",
    "Food Science and Nutrition Bachelor",
    "Food Science and Nutrition Master",
    "Food Science TC",
    "Geography Teaching Diploma",
    "Geomatics Master",
    "Geospatial Engineering Bachelor",
    "Health Sciences and Technology Bachelor",
    "Health Sciences and Technology Master",
    "Health Sciences and Technology TC",
    "High-Energy Physics (Joint Master with IP Paris)",
    "History and Philosophy of Knowledge Master",
    "Humanities, Social and Political Sciences (General Courses)",
    "Human Medicine Bachelor",
    "Integrated Building Systems Master",
    "Interdisciplinary Brain Sciences Master",
    "Interdisciplinary Sciences Bachelor",
    "Interdisciplinary Sciences Master",
    "Landscape Architecture Master",
    "Management, Technology and Economics (General Courses)",
    "Management, Technology and Economics Master",
    "MAS in Advanced Fundamentals of Mechatronics Engineering",
    "MAS in AI and Digital Technology",
    "MAS in Applied Technology",
    "MAS in Architecture and Digital Fabrication",
    "MAS in Built Heritage and Repair",
    "MAS in Cyber Security",
    "MAS in Digital Clinical Research",
    "MAS in Fire Safety Engineering",
    "MAS in Future Transport Systems",
    "MAS in Global Cooperation and Sustainable Development",
    "MAS in History and Theory of Architecture (GTA)",
    "MAS in Management, Technology, and Economics",
    "MAS in Medical Physics",
    "MAS in Nutrition and Health",
    "MAS in Preservation and Construction History",
    "MAS in Spatial Development",
    "MAS in Technology and Public Policy",
    "MAS in Urban and Territorial Design",
    "MAS Mediation in Peace Processes",
    "Materials Science Bachelor",
    "Materials Science Master",
    "Mathematics Bachelor",
    "Mathematics Education Master",
    "Mathematics (General Courses)",
    "Mathematics Master",
    "Mathematics TC",
    "Mathematics Teaching Diploma",
    "Mechanical and Process Engineering TC",
    "Mechanical Engineering Bachelor",
    "Mechanical Engineering Master",
    "Mechatronics Engineering Master Ashesi University",
    "Micro- and Nanosystems Master",
    "Neural Systems and Computation Master",
    "Nuclear Engineering Master",
    "Pharmaceutical Sciences Bachelor",
    "Pharmaceutical Sciences Master",
    "Pharmacy Master",
    "Physics Bachelor",
    "Physics (General Courses)",
    "Physics Master",
    "Physics TC",
    "Physics Teaching Diploma",
    "Process Engineering Master",
    "Project Mobility",
    "Public Policy Bachelor",
    "Quantitative Finance Master",
    "Quantum Engineering Master",
    "Robotics, Systems and Control Master",
    "Science Education Master",
    "Science in Perspective",
    "Science, Technology, and Policy Master",
    "Space Systems Master",
    "Spatial Development and Infrastructure Systems Master",
    "Sport Teaching Diploma",
    "Statistics Master"
]