
json_format = {
    # Correct names
    "course_id":                {"en": "Course ID",                                      "de": "Kurs ID"},
    "title":                    {"en": "Course title",                                   "de": "Kursname"},
    "semester":                 {"en": "Semester",                                       "de": "Semester"},
    "periodicity":              {"en": "Periodicity",                                    "de": "Periodizität"},
    "language_of_instruction":  {"en": "Language of instruction",                        "de": "Lehrsprache"},
    "lecturers":                {"en": "Lecturers",                                      "de": "Dozierende"},
    "comment":                  {"en": "Comment",                                        "de": "Kommentar"},
    
    
    "classes":                  {"en": "Courses",                                        "de": "Lehrveranstaltungen"},
    "class_type":               {"en": "Number",                                         "de": "Nummer"},
    "hours_per_week":           {"en": "Hours per week",                                 "de": "Stunden pro Woche"},
    "schedule":                 {"en": "Schedule",                                       "de": "Stundenplan"},
    "day":                      {"en": "Day",                                            "de": "Tag"},
    "time":                     {"en": "Time",                                           "de": "Zeit"},
    "venue":                    {"en": "Venue",                                          "de": "Ort"},
    "notes":                    {"en": "Notes",                                          "de": "Bemerkungen"},
    
    # Correct names
    "catalogue_data":           {"en": "Catalogue data",                                 "de": "Katalogdaten"},
    "description":              {"en": "Abstract",                                       "de": "Kurzbeschreibung"},
    "learning_objectives":      {"en": "Learning objective",                             "de": "Lernziel"},
    "content":                  {"en": "Content",                                        "de": "Inhalt"},
    "lecture_notes":            {"en": "Lecture notes",                                  "de": "Skript"},
    "literature":               {"en": "Literature",                                     "de": "Literatur"},
    "prerequisites":               {"en": "Prerequisites / Notice",                      "de": "Voraussetzungen / Besonderes"},
    # Correct names
    "performance_assessment":   {"en": "Performance assessment",                         "de": "Leistungskontrolle"},
    "ects_credits":             {"en": "ECTS credits",                                   "de": "ECTS Kreditpunkte"},
    "assessment_type":          {"en": "Type",                                           "de": "Form"},
    "language_of_examination":  {"en": "Language of examination",                        "de": "Prüfungssprache"},
    "repetition":               {"en": "Repetition",                                     "de": "Repetition"},
    "examination":              {"en": "Mode of examination",                            "de": "Prüfungsmodus"},
    "additional_info":          {"en": "Additional information on mode of examination",  "de": "Zusatzinformation zum Prüfungsmodus	"},
    "exam_aid":                 {"en": "Written aids",                                   "de": "Hilfsmittel schriftlich"},
    
    "regulations":              {"en": "For programme regulations(Examination block)",   "de": "Für Reglement(Prüfungsblock)"},
    "examination_block":        {"en": "In examination block",                           "de": "Im Prüfungsblock für"},
    
    # Correct names
    "offered_in":               {"en": "Offered in",                                     "de": "Angeboten in"},
    "program":                  {"en": "Programme",                                      "de": "Studiengang"},
    "section":                  {"en": "Section",                                        "de": "Bereich"},
    "type":                     {"en": "Type",                                           "de": "Typ"}
}

level_studies = {
    "" : "-",
    "WBZ" : "Advanced Studies (CAS, DAS)", 
    "BSC" : "Bachelor's Degree Programme", 
    "DS" : "Diploma Programme", 
    "DR" : "Doctorate", 
    "NDS" : "Master of Advanced Studies", 
    "MSC" : "Master's Degree Programme", 
    "GS" : "Mobility Students", 
    "DZ" : "Teaching Certificate", 
    "SHE" : "Teaching Diploma", 
}

departments = {
    "" : "-",
    "1" : "Architecture", 
    "11" : "Biology", 
    "23" : "Biosystems Science and Engineering", 
    "20" : "Chemistry and Applied Biosciences", 
    "2" : "Civil, Environmental and Geomatic Engineering", 
    "5" : "Computer Science", 
    "13" : "Earth and Planetary Sciences", 
    "25" : "Environmental Systems Science", 
    "24" : "Health Sciences and Technology", 
    "17" : "Humanities, Social and Political Sciences", 
    "18" : "Information Technology and Electrical Engineering", 
    "7" : "Management, Technology, and Economics", 
    "19" : "Materials", 
    "8" : "Mathematics", 
    "3" : "Mechanical and Process Engineering", 
    "9" : "Physics"
}


university_programs = {
"117361": "Agricultural Sciences Bachelor",
"117383": "Agricultural Sciences Master",
"117398": "Agricultural Sciences TC",
"117389": "Applied Geophysics Master",
"117364": "Architecture Bachelor",
"117413": "Architecture Master",
"117387": "Atmospheric and Climate Science Master",
"117491": "Biochemistry – Chemical Biology Bachelor",
"117511": "Biochemistry - Chemical Biology Master",
"117358": "Biology Bachelor",
"117412": "Biology (General Courses)",
"117380": "Biology Master",
"117403": "Biology Teaching Diploma",
"117372": "Biomedical Engineering Master",
"117459": "Biotechnology Master",
"117479": "CAS in Advanced Materials and Processes",
"117482": "CAS in Applied Earth Sciences",
"117485": "CAS in Applied Machine Learning &amp; Information Processing",
"117460": "CAS in Applied Statistical Data Science",
"117488": "CAS in Applied Technology: R&amp;D and Innovation",
"119861": "CAS in Artificial Intelligence and Software Development",
"120027": "CAS in Cloud and Mobile Computing",
"117426": "CAS in Computer Science",
"117478": "CAS in Cyber Security",
"117521": "CAS in Data and Machine Learning",
"117505": "CAS in Digital Clinical Trials",
"117498": "CAS in Digital Health",
"117492": "CAS in Entrepreneurial Leadership in Technology Ventures",
"117510": "CAS in Future Heritage",
"117518": "CAS in Future of Spatial Development",
"117509": "CAS in Future Transport Systems: New Business Models",
"117508": "CAS in Future Transport Systems: Systemic Aspects",
"117461": "CAS in Future Transport Systems: Technology Potential",
"117513": "CAS in Geoinformation Systems and Analysis",
"117470": "CAS in Global Cooperation and Sustainable Development",
"119981": "CAS in Infrastructure Construction Management",
"117519": "CAS in Machine Learning in Finance and Insurance",
"117453": "CAS in Nutrition for Disease Prevention and Health",
"117507": "CAS in Nutrition in Medicine",
"117473": "CAS in Pharmaceuticals - From Research to Market",
"117501": "CAS in Preservation",
"117471": "CAS in Public Governance and Administration",
"117472": "CAS in Radiopharmaceutical Chemistry, Radiopharmacy",
"117497": "CAS in Regenerative Materials - Hygrothermal Specialisation",
"117523": "CAS in Regenerative Materials - Structural Specialisation",
"117516": "CAS in Regenerative Systems: Beyond Systems Thinking",
"117514": "CAS in Regenerative Systems: Sustainability to Regeneration",
"117524": "CAS in Regenerative Systems: Systemic Design",
"117506": "CAS in Regulatory Thinking",
"117494": "CAS in Robotics",
"117495": "CAS in Seismic Evaluation and Retrofitting",
"117465": "CAS in Spatial Development and Planning Practice",
"117493": "CAS in Technology and Public Policy: Impact Analysis",
"117520": "CAS in Technology and Public Policy: Policy Process",
"117371": "Chemical and Bioengineering Master",
"117390": "Chemical Engineering Bachelor",
"117350": "Chemistry Bachelor",
"117344": "Chemistry (General Courses)",
"117370": "Chemistry Master",
"117404": "Chemistry Teaching Diploma",
"117352": "Civil Engineering Bachelor",
"117341": "Civil Engineering (General Courses)",
"117375": "Civil Engineering Master",
"117388": "Comparative and International Studies Master",
"117414": "Computational Biology and Bioinformatics Master",
"117347": "Computational Science and Engineering Bachelor",
"117369": "Computational Science and Engineering Master",
"117354": "Computer Science Bachelor",
"117342": "Computer Science (General Courses)",
"117378": "Computer Science Master",
"117395": "Computer Science TC",
"117394": "Computer Science Teaching Diploma",
"117484": "Cyber Security Master",
"117462": "DAS in Applied Statistical Data Science",
"117477": "DAS in Cyber Security",
"117480": "DAS in Data Science",
"117447": "DAS in Information Technology and Electrical Engineering",
"117452": "DAS in Military Sciences",
"117512": "DAS in Regenerative Materials",
"117448": "DAS Preparation for the Swiss Federal Examination in Pharmacy",
"117466": "Data Science Master",
"117436": "Doctorate Architecture",
"117437": "Doctorate Biology",
"117438": "Doctorate Biosystems Science and Engineering",
"117431": "Doctorate Chemistry and Applied Biosciences",
"117433": "Doctorate Civil, Environmental and Geomatic Engineering",
"117441": "Doctorate Computer Science",
"117439": "Doctorate Earth and Planetary Sciences",
"117432": "Doctorate Environmental Systems Sciences",
"117451": "Doctorate Health Sciences and Technology",
"117440": "Doctorate Humanities, Social and Political Sciences",
"117442": "Doctorate Information Technology and Electrical Engineering",
"117443": "Doctorate Management, Technology, and Economics",
"117445": "Doctorate Materials Science",
"117430": "Doctorate Mathematics",
"117444": "Doctorate Mechanical and Process Engineering",
"117446": "Doctorate Physics",
"117359": "Earth and Climate Sciences Bachelor",
"117381": "Earth Sciences Master",
"117391": "Educational Science for Teaching Diploma and TC",
"117363": "Electrical Engineering and Information Technology Bachelor",
"117415": "Electrical Engineering and Information Technology Master",
"117399": "Electrical Engineering and Information Technology TC",
"117515": "EMBA ETH HSG (emba X)",
"117416": "Energy Science and Technology Master",
"117353": "Environmental Engineering Bachelor",
"117376": "Environmental Engineering Master",
"117360": "Environmental Sciences Bachelor",
"117382": "Environmental Sciences Master",
"117402": "Environmental Studies TC",
"117362": "Food Science and Nutrition Bachelor",
"117384": "Food Science and Nutrition Master",
"117400": "Food Science TC",
"117405": "Geography Teaching Diploma",
"117377": "Geomatics Master",
"117476": "Geospatial Engineering Bachelor",
"117434": "Health Sciences and Technology Bachelor",
"117454": "Health Sciences and Technology Master",
"117456": "Health Sciences and Technology TC",
"117429": "High-Energy Physics (Joint Master with IP Paris)",
"117421": "History and Philosophy of Knowledge Master",
"117345": "Humanities, Social and Political Sciences (General Courses)",
"117464": "Human Medicine Bachelor",
"117455": "Integrated Building Systems Master",
"117503": "Interdisciplinary Brain Sciences Master",
"117365": "Interdisciplinary Sciences Bachelor",
"117420": "Interdisciplinary Sciences Master",
"117487": "Landscape Architecture Master",
"117425": "Management, Technology and Economics (General Courses)",
"117373": "Management, Technology and Economics Master",
"117500": "MAS in Advanced Fundamentals of Mechatronics Engineering",
"117522": "MAS in AI and Digital Technology",
"117486": "MAS in Applied Technology",
"117458": "MAS in Architecture and Digital Fabrication",
"120021": "MAS in Built Heritage and Repair",
"120001": "MAS in Cyber Security",
"117504": "MAS in Digital Clinical Research",
"117490": "MAS in Fire Safety Engineering",
"117463": "MAS in Future Transport Systems",
"117419": "MAS in Global Cooperation and Sustainable Development",
"117449": "MAS in History and Theory of Architecture (GTA)",
"117407": "MAS in Management, Technology, and Economics",
"117411": "MAS in Medical Physics",
"117409": "MAS in Nutrition and Health",
"117502": "MAS in Preservation and Construction History",
"117410": "MAS in Spatial Development",
"117499": "MAS in Technology and Public Policy",
"117496": "MAS in Urban and Territorial Design",
"117474": "MAS Mediation in Peace Processes",
"117351": "Materials Science Bachelor",
"117368": "Materials Science Master",
"117355": "Mathematics Bachelor",
"117489": "Mathematics Education Master",
"117343": "Mathematics (General Courses)",
"117379": "Mathematics Master",
"117396": "Mathematics TC",
"117392": "Mathematics Teaching Diploma",
"117401": "Mechanical and Process Engineering TC",
"117348": "Mechanical Engineering Bachelor",
"117366": "Mechanical Engineering Master",
"117525": "Mechatronics Engineering Master Ashesi University",
"117386": "Micro- and Nanosystems Master",
"117423": "Neural Systems and Computation Master",
"117422": "Nuclear Engineering Master",
"117357": "Pharmaceutical Sciences Bachelor",
"117467": "Pharmaceutical Sciences Master",
"117468": "Pharmacy Master",
"117356": "Physics Bachelor",
"117408": "Physics (General Courses)",
"117418": "Physics Master",
"117397": "Physics TC",
"117393": "Physics Teaching Diploma",
"117367": "Process Engineering Master",
"117374": "Project Mobility",
"117349": "Public Policy Bachelor",
"117428": "Quantitative Finance Master",
"117483": "Quantum Engineering Master",
"117427": "Robotics, Systems and Control Master",
"117435": "Science Education Master",
"117346": "Science in Perspective",
"117457": "Science, Technology, and Policy Master",
"117517": "Space Systems Master",
"117385": "Spatial Development and Infrastructure Systems Master",
"117406": "Sport Teaching Diploma",
"117417": "Statistics Master"
}